apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dotnet60-basic-ikse
  namespace: pshivpuj-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:c703e374199c7b4ace9a0f18bef55b67d380feb831fe3293d6530f15674cb75d
        name: main
        resources: {}
status: {}
